// Code generated by go-imbed. DO NOT EDIT.

#include "textflag.h"

TEXT ·blob_bytes(SB),NOSPLIT,$0-8
	MOVD	$·d(SB), R0
	MOVD	R0, ret+8(FP)
	MOVW	len+0(FP), R0
	MOVD	R0, ret+16(FP)
	MOVD	R0, ret+24(FP)
	RET

TEXT ·blob_string(SB),NOSPLIT,$0-8
	MOVD	$·d(SB), R0
	MOVD	R0, ret+8(FP)
	MOVD	len+0(FP), R0
	MOVD	R0, ret+16(FP)
	RET
