// Code generated by go-imbed. DO NOT EDIT.

// +build mips64 mips64le

#include "textflag.h"

TEXT ·blob_bytes(SB),NOSPLIT,$0-8
	MOVV	$·d(SB), R1
	MOVV	R1, ret+8(FP)
	MOVV	len+0(FP), R1
	MOVV	R1, ret+16(FP)
	MOVV	R1, ret+24(FP)
	JMP	(R31)

TEXT ·blob_string(SB),NOSPLIT,$0-8
	MOVV	$·d(SB), R1
	MOVV	R1, ret+8(FP)
	MOVV	len+0(FP), R1
	MOVV	R1, ret+16(FP)
	JMP	(R31)
