// Code generated by go-imbed. DO NOT EDIT.

#include "textflag.h"

TEXT ·blob_bytes(SB),NOSPLIT,$0-4
	LEAQ	·d(SB), AX
	MOVQ	AX, ret+8(FP)
	MOVL	len+0(FP), AX
	MOVLQSX	AX, AX
	MOVQ	AX, ret+16(FP)
	MOVQ	AX, ret+24(FP)
	RET

TEXT ·blob_string(SB),NOSPLIT,$0-4
	LEAQ	·d(SB), AX
	MOVQ	AX, ret+8(FP)
	MOVL	len+0(FP), AX
	MOVLQSX	AX, AX
	MOVQ	AX, ret+16(FP)
	RET
