// Code generated by go-imbed. DO NOT EDIT.

#include "textflag.h"

TEXT ·blob_bytes(SB),NOSPLIT,$0-4
	MOVW	$·d(SB), R0
	MOVW	R0, ret+4(FP)
	MOVW	len+0(FP), R0
	MOVW	R0, ret+8(FP)
	MOVW	R0, ret+12(FP)
	RET

TEXT ·blob_string(SB),NOSPLIT,$0-4
	MOVW	$·d(SB), R0
	MOVW	R0, ret+4(FP)
	MOVW	len+0(FP), R0
	MOVW	R0, ret+8(FP)
	RET
