// Code generated by go-imbed. DO NOT EDIT.

#include "textflag.h"

TEXT ·blob_bytes(SB),NOSPLIT,$0-4
	LEAL	·d(SB), AX
	MOVL	AX, ret+4(FP)
	MOVL	len+0(FP), AX
	MOVL	AX, ret+8(FP)
	MOVL	AX, ret+12(FP)
	RET

TEXT ·blob_string(SB),NOSPLIT,$0-4
	LEAL	·d(SB), AX
	MOVL	AX, ret+4(FP)
	MOVL	len+0(FP), AX
	MOVL	AX, ret+8(FP)
	RET
